server:
  port: 9999

spring:
  config:
    activate:
      on-profile: company
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:/spring_workspace/sailing_spring/h2
    username: sa
    password: sa
